#0F1418

$foreground = rgb(afbdc9)
$background = rgb(0F1418)
$wallpaper = rgb(home/thinkpad/Pictures/wallpapers/wallhaven-9ode5x.jpg)

$color0 = rgb(0F1418)
$color1 = rgb(324559)
$color2 = rgb(395067)
$color3 = rgb(475E74)
$color4 = rgb(C77270)
$color5 = rgb(3E6280)
$color6 = rgb(58728A)
$color7 = rgb(afbdc9)
$color8 = rgb(7a848c)
$color9 = rgb(324559)
$color10 = rgb(395067)
$color11 = rgb(475E74)
$color12 = rgb(C77270)
$color13 = rgb(3E6280)
$color14 = rgb(58728A)
$color15 = rgb(afbdc9) 