#0a0807

$foreground = rgb(e0d2cc)
$background = rgb(0a0807)
$wallpaper = rgb(home/thinkpad/Pictures/wallpapers/wallhaven-lyzly2.jpg)

$color0 = rgb(0a0807)
$color1 = rgb(665757)
$color2 = rgb(C22117)
$color3 = rgb(8E6C68)
$color4 = rgb(AB926B)
$color5 = rgb(897B91)
$color6 = rgb(AC9792)
$color7 = rgb(e0d2cc)
$color8 = rgb(9c938e)
$color9 = rgb(665757)
$color10 = rgb(C22117)
$color11 = rgb(8E6C68)
$color12 = rgb(AB926B)
$color13 = rgb(897B91)
$color14 = rgb(AC9792)
$color15 = rgb(e0d2cc) 