#030203

$foreground = rgb(d5d1d9)
$background = rgb(030203)
$wallpaper = rgb(home/thinkpad/Pictures/wallpapers/wallhaven-3q3e3y.jpg)

$color0 = rgb(030203)
$color1 = rgb(978679)
$color2 = rgb(C3847D)
$color3 = rgb(837789)
$color4 = rgb(AD9E92)
$color5 = rgb(C9B3A7)
$color6 = rgb(D4C5B9)
$color7 = rgb(d5d1d9)
$color8 = rgb(959297)
$color9 = rgb(978679)
$color10 = rgb(C3847D)
$color11 = rgb(837789)
$color12 = rgb(AD9E92)
$color13 = rgb(C9B3A7)
$color14 = rgb(D4C5B9)
$color15 = rgb(d5d1d9) 