source = ~/.config/hypr/settings/monitors.conf
source = ~/.config/hypr/settings/programs.conf
source = ~/.config/hypr/settings/startup.conf
source = ~/.config/hypr/settings/env.conf
source = ~/.config/hypr/settings/permissions.conf
source = ~/.config/hypr/look/general.conf
source = ~/.config/hypr/look/decoration.conf
source = ~/.config/hypr/look/animations.conf
source = ~/.config/hypr/keybinds/input.conf
source = ~/.config/hypr/keybinds/keybinds.conf
source = ~/.config/hypr/settings/windowrule.conf
